### ISSUE TITLE
Doc examples don't run

### ISSUE THREAD

**Issue by hwine** [dcbaker/jsonstreams#13]
The argument order to ``jsonstreams.Stream`` got changed somewhere along the line, but the docs weren't updated to match.

Correct example:
```python
import jsonstreams

mylist = list(range(10))
mydict = {a: b for a in range(10) for b in 'abcdefghij'}

with jsonstreams.Stream(jsonstreams.Type.object, 'foo') as s:
    s.write('list', mylist)
    s.write('dict', mydict)
```

**Comment by dcbaker** [comment]
you're correct, and the array example in the README is incorrect as well.
