### ISSUE TITLE
jsonstreams.Stream should not close file descriptors when leaving context if we instantiated jsonstreams.Stream with one

### ISSUE THREAD

**Issue by JonoYang** [dcbaker/jsonstreams#23]
If I instantiate `jsonstreams.Stream` with a file descriptor that I made or am using from somewhere else, i.e.

```
fd = open('somefile.json', 'w')
with jsonstreams.Stream(jsonstreams.Type.object, fd=output_file) as s:
...
```

the file descriptor `fd` is closed when I leave the `jsonstreams.Stream` context (https://github.com/dcbaker/jsonstreams/blob/master/jsonstreams/__init__.py#L568). I'd expect the file descriptor `fd` to be open when I leave the context, so I can manage `fd` myself. 

I ran into this problem using a file descriptor managed by click (https://click.palletsprojects.com/en/7.x/api/?highlight=file#click.File), where `jsonstreams.Stream` closed the descriptor before click was finished with it.

I had to do a hack, where I finish the `jsonstreams.Stream` object by calling `_Stream__inst.Close()` and leaving the file descriptor open so click can deal with it (https://github.com/nexB/scancode-toolkit/blob/2303-stream-json-output/src/formattedcode/output_json.py#L178)

**Comment by dcbaker** [comment]
You're right, we really shouldn't close a file descriptor if we didn't open it. I'll have to think about how to track that.
