### ISSUE TITLE
Early 0.4.4 release possible?

### ISSUE THREAD

**Issue by JonoYang** [dcbaker/jsonstreams#28]
I understand that you are still working on #20, but I was hoping that you would be able to make an early release of 0.4.4 for jsonstreams available on pypi. I would like to use the recent updates from #22 and #25 in our upcoming November release of https://github.com/nexB/scancode-toolkit. Otherwise, we will have to fork jsonstreams with the updates and upload it to pypi so a version of jsonstreams with the fixes can be available for use in our software. 

Thank you for the time and effort you have put into this great project!

**Comment by dcbaker** [comment]
I've gotten the release done now, and 0.5.0 uploaded to pypi (sorry for the delay, I had some computer issues, then couldn't get twine to work for uploading the release.) Should be good to go now.

**Comment by JonoYang** [comment]
Much appreciated! Again, thank you
