### ISSUE TITLE
Tag for 0.5.0

### ISSUE THREAD

**Issue by chkno** [dcbaker/jsonstreams#29]
I see a commit on main c88e1edbbc7d558c0256ef137ec71869c6d4b4f7 that says "Bump version: 0.4.3 → 0.5.0", but I don't see a 0.5.0 tag [in the public github repo](https://github.com/dcbaker/jsonstreams/tags).

**Comment by dcbaker** [comment]
Oops, you're right. The 0.4.3 tag didn't get pushed either. I've pushed both of them now.
