### ISSUE TITLE
Stream ignores custom json.JSONEncoder separators argument

### ISSUE THREAD

**Issue by TrevinAvery** [dcbaker/jsonstreams#35]
When using a custom `json.JSONEncoder`, the output ignores the `separators` argument.

Example: Using separators with no spaces to minify file size.

```
import json, jsonstreams

def encoder(*args, **kwargs): 
    return json.JSONEncoder(separators=(',', ':')) 

with jsonstreams.Stream(jsonstreams.Type.object, 'out.json', encoder=encoder) as s:
    s.write('key', 'value')
```

Observed `out.json`
```
{"key": "value"}
```

Expected `out.json`
```
{"key":"value"}
```

**Comment by dcbaker** [comment]
Can confirm that this doesn't work.

**Comment by dcbaker** [comment]
Can you confirm if #35 fixes this for you?

**Comment by TrevinAvery** [comment]
Perfect. That appears to have fixed it.

**Comment by dcbaker** [comment]
Thanks!
