### ISSUE TITLE
Tag for 0.6.0

### ISSUE THREAD

**Issue by chkno** [dcbaker/jsonstreams#42]
I see a commit on main 123db38180db406ee68bf6db204810af8a0d6f13 that says "Bump version: 0.5.0 → 0.6.0", but I don't see a 0.6.0 tag in the [public github repo](https://github.com/dcbaker/jsonstreams/tags).

(Same as https://github.com/dcbaker/jsonstreams/issues/29)

Thanks!

**Comment by dcbaker** [comment]
Gah, I'm terrible at remembering to push tags. Fixed now, thanks
